export default {
    GET_LIST_FILMS_REQUEST: "GET_LIST_FILMS_REQUEST",
    GET_LIST_FILMS_SUCCESS: "GET_LIST_FILMS_SUCCESS",
    GET_LIST_FILMS_FAILURE: "GET_LIST_FILMS_FAILURE",
    CLEAR_CURRENT_FILM: "CLEAR_CURRENT_FILM",
    CURRENT_FILM: "CURRENT_FILM",
    EDIT_POPUP: "EDIT_POPUP",
    DETAIL_POPUP: "DETAIL_POPUP",
}